### ISSUE TITLE
Kernel - GPL but what about uboot

### ISSUE THREAD

**Issue by bleprotocols** [facebookincubator/oculus-linux-kernel#5]
Hello, you've made your changes to the linux kernel open source. But the Oculus Go uses another GPL'd piece of software called uboot - the bootloader. Are you planning on making this open source as well?

**Comment by intervigilium** [comment]
Oculus Go does not use uboot (assuming you mean https://github.com/u-boot/u-boot ?). There are no plans to open source the Oculus Go bootloader.
