### ISSUE TITLE
(Question) Does this repo contain anything beyond a base kernel for the Quest?

### ISSUE THREAD

**Issue by zodiepupper** [facebookincubator/oculus-linux-kernel#6]
If I were to use this kernel to test some applications I am developing for the Quest, how could I go about that?
Does this repo contain anything involving the tracking solution or any other main functionalities of the hardware? 
Is there an API available in this repo that one could use for getting the tracking data?

I'm interested in contributing to this project, but I need some of this info so I know what level of work needs to be done before I can start developing directly to the lowest level for the Oculus Quest.

Thank you.

**Comment by intervigilium** [comment]
This repository consists of only the Linux kernel. Running compiled code from this repository requires a developer headset with secure boot disabled. If you have a locked retail Quest device you will probably not be able to run the compiled code in this repository.
